### ISSUE TITLE
Possible file leak causes traefik to fail with too many open files

### ISSUE THREAD

**Issue by stevendborrelli** [emilevauge/traefik#127]
We've seen this a couple of times in our clusters. It's possible that traefik is not releasing file descriptors. 

```
traefik --version
400655f212690cb4204bf36dee0ffca87c21bfb5 built on the 2015-11-13_08:54:04AM
```
```
Nov 24 14:03:29 eu-control-02 traefik[14890]: 2015/11/24 14:03:29 server.go:1934: http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 320ms

Nov 24 14:03:31 eu-control-02 traefik[14890]: time="2015-11-24T14:03:31Z" level=fatal msg="Error hijacking server file tcp [::]:80: fcntl: too many open files"
```

**Comment by emilevauge** [comment]
Hi @stevendborrelli, after some tests, it seems that it's due to https://github.com/golang/go/issues/6785:

> My theory, after going through the http.Transport, is that when the number of requests/s
to the proxy goes up, the small amount of bookkeeping that is required to recycle a
connection (putIdleConn etc) starts taking just long enough that the next request in the
pipeline gets in before a connection is idle. The Transport starts Dial:ing, adding more
connections to take care of, and it explodes chaotically. I would prefer if it blocked
and awaited an idle connection instead of Dial:ing at some point.

A workaround is to set a `MaxIdleConnsPerHost` to the `Transport`. I tested it on my laptop and the issue is gone :) I will add an option in configuration to allow tuning this setting.

**Comment by zinob** [comment]
I don't know if this is the same issue but despite upgrading to the latest traefik (the dip near the start of the graph) this problem persists in our environment. The previously mentioned work-around of setting MaxIdleConnsPerHost does not help. I am unable to reproduce it in the test-environement which makes diagnosing it harder. 
![omgwtffilepointers](https://cloud.githubusercontent.com/assets/3193966/23018751/7e6f7e40-f43f-11e6-90a6-528fd09dc00f.png) .
Since the Linux Kernel can handle a ridiculous number of open files and servers needs to be rebooted every now and then anyway this is not really a problem, I am mostly noting it here for posterity.

snippet from lsof:
```
COMMAND      PID       USER   FD      TYPE             DEVICE  SIZE/OFF       NODE NAME
traefik    91086       root  235u     sock                0,7       0t0 2774592774 can't identify protocol
traefik    91086       root  236u     sock                0,7       0t0 1192344780 can't identify protocol
traefik    91086       root  237u     sock                0,7       0t0 1188443220 can't identify protocol
traefik    91086       root  238u     sock                0,7       0t0   74969846 can't identify protocol
traefik    91086       root  239u     sock                0,7       0t0  312444077 can't identify protocol
traefik    91086       root  240u     sock                0,7       0t0  454676095 can't identify protocol
traefik    91086       root  241u     sock                0,7       0t0  348959376 can't identify protocol
```

**Comment by IncSW** [comment]
Hi. Same problem in docker container based on alpine `traefik:morbier-alpine`.
`MaxIdleConnsPerHost = 200`
`ulimit -n // 65536`

With ~100rps, after 24h takes limit.
