### ISSUE TITLE
Atomic configuration updates with etcd, consul, or any kv store.

### ISSUE THREAD

**Issue by kevioke** [emilevauge/traefik#191]
Hi All,

We are interested in using Traefik as a load balancer for our many microservices. One of the requirements however, is to also be able to support Canary deployments. We want to do this by leveraging the weights configuration for the backends in Traefik.

The problem we are facing is that the key value stores that Traefik supports doesn't seem to allow atomic transactions. We want to be able to specify a configuration atomically as a whole instead of pieces of it.

Example:
**/traefik/backends/backend1/servers/server1/weight 	10**
**/traefik/backends/backend1/servers/server2/weight 	5**
**/traefik/backends/backend1/servers/server3/weight 	1**

Suppose we wanted to change the weights to be evenly distributed. Since the key value stores do not support atomic transactions, we can potentially end up in a state where Traefik reads wrong configuration before we have time to finalize the weights that we actually want.

We want Traefic to be this:

**/traefik/backends/backend1/servers/server1/weight 	1**
**/traefik/backends/backend1/servers/server2/weight 	1**
**/traefik/backends/backend1/servers/server3/weight 	1**

But it can end up reading this:

**/traefik/backends/backend1/servers/server1/weight 	1**
**/traefik/backends/backend1/servers/server2/weight 	5**
**/traefik/backends/backend1/servers/server3/weight 	1**

This is just one of the configuration keys that we think can be affected with non-atomic configuration writes. There may be others such as the server url configuration key. What would you recommend as a good way to ensure configuration consistency?

We are considering using the Traefik rest API and creating a separate application which sends a PUT to Traefik with the entire configuration each time we want to update it. This will work, but we wanted to know if there were any better alternatives which utilizes the internal Key Value providers which seems like a cleaner approach.

**Comment by emilevauge** [comment]
Hi @kevioke, this is an issue that I'm aware of.
A possible workaround would be to use the [ProvidersThrottleDuration](https://github.com/emilevauge/traefik/blob/master/docs/index.md#global):
> Backends throttle duration: minimum duration between 2 events from providers
before applying a new configuration. It avoids unnecessary reloads if multiples events
are sent in a short amount of time.

If you set it for example to `5s`, if you change 10 times successively your etcd keys (with less than 5s between each change), only the last received configuration will be applied be traefik.

It's not atomic, but, it's kind of ;)
Would that be acceptable for you?

**Comment by kevioke** [comment]
@emilevauge, thank you so much for the quick response. I was not aware of this configuration which seems potentially useful.

However, I am hesitant to use this work around because it still seems brittle for us. We plan on using Traefik for hundreds of different micro services and would definitely prefer stronger consistency. Suppose some network event occurs in the middle of updating one of the keys. Upon recovery, we would need to know how to fix the keys to be in a consistent state. During a dependency failure, we can be in an inconsistent state for a long time.

There is also a potential problem with the first key that is updated. That key update will always cause a reload because the previous configuration update happened a long time ago. Only the following key updates will buffer.

We are also looking at a couple other techniques.

1. Use the "web" provider and leverage the REST apis to update the configuration atomically. We need a separate service for this :(
2. Write our own Provider that uses a different key, value format which allows for consistency. For example, but all the config under one key :P
3. Use the "file" provider, and somehow update all Traefik hosts to have the same file. Maybe via NFS?

I'd love to know what your thoughts are with some of these. Are there things that Traefik has on the roadmap that will make this use case easier for clients?

**Comment by emilevauge** [comment]
> There is also a potential problem with the first key that is updated. That key update will always cause a reload because the previous configuration update happened a long time ago. Only the following key updates will buffer.

Nope, when traefik receive an event, he waits for `2s` (ProvidersThrottleDuration) before applying it.

I perfectly understand that you would prefer something more accurate. But, the issue is more on KV stores than on Traefik and I don't see any magic trick to solve this issue.

I think that the best solution in your case would be the 1/.
2/ You would also need a separate service that would put the BIG key in etcd, like in 1/.
3/ Not fan of this, more complex than 1/

If I have a better idea, I will let you know ;)

**Comment by kevioke** [comment]
Ah my mistake on the ProvidersThrottleDuration. Thanks a lot for your input, I will share your feedback with our team.

**Comment by advait** [comment]
@emilevauge Surely you agree that `ProvidersThrottleDuration` is a hack, no? I think we can solve this problem elegantly by using pointers.

I propose a new key called `/traefik/configuration_prefix` whose value indicates the subtree in which to load the remaining configuration from. By default, it should be the empty string, denoting that the configuration should be loaded from the `/traefik/` prefix.

Alternatively, the `/traefik/configuration_prefix` can be non-empty. Suppose its value is `1455498702143`. This will denote that traefik should load its configuration from the `/traefik/1455498702143/` prefix. When an atomic update is required, rather than updating keys with the existing prefix, you can write new keys to a sibling prefix like `/traefik/1455498886987/`. When the writes complete and the new configuration is fully set, you can update the `/traefik/configuration_prefix` key to be `1455498886987` causing Traefik to read from the new subtree.

This lends itself to numerous advantages:

1. It is impossible to read an intermediate state because the `/traefik/1455498702143/` subtree and all of its sibling subtrees would be immutable. Further, updates to the `/traefik/configuration_prefix` are atomic causing configuration to change from one immutable subtree to the next.
2. We can set `ProvidersThrottleDuration` to zero, reducing the delay of new configurations to take hold.
3. Existing users of Traefik will be unaffected as the `/traefik/configuration_prefix` will default to the empty string resulting Traefik's current behavior.

We are in the process of evaluating Traefik for full production needs and this is a blocker for us. We would be more than happy to send you a fully tested PR with the above proposal if you give us the thumbs up!

**Comment by emilevauge** [comment]
Hi @advait, great and simple idea!
I think this is the simplest way to get generic atomic KV updates.
I would prefer `/traefik/alias` over `/traefik/configuration_prefix` ;)
And that new key would contain the full path to the configuration:
`/traefik/alias` : `/traefik/1455498702143`
WDYT ? 
cc @vdemeester

**Comment by advait** [comment]
Awesome! I agree regarding `/traefik/alias` (both name as well as value).

I think we should continue the KV `WatchTree` of the `/traefik` subtree. Further, I think we should also recommend that others place their real configurations _outside_ of the `/traefik` subtree. For example, `/traefik/alias` should be set to `/traefik_configurations/1455498702143`. This will prevent spurious `WatchTree` events in the `/traefik` subtree as one builds up a new configuration.

Finally, to encourage immutability, I think we should _not_ `WatchTree` the subtree pointed to by `/traefik/alias`. Change events should only fire when `/traefik` keys change - not when `/traefik_configurations/` keys change.

Thoughts?

**Comment by emilevauge** [comment]
I totally agree, don't watch the subtree pointed by alias :)

**Comment by vdemeester** [comment]
@advait @emilevauge LGTM :wink: :+1:
